POST http://localhost:3000/register
content-type: application/json

{
  "username": "vijay",
  "name": "Adam Richard",
  "password": "vijay_567",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login
content-type: application/json

{
  "username": "dam_richard",
  "password": "richard@123"
}

###
PUT http://localhost:3000/change-password
content-type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}